# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more informatioon see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main, develop, feature/*, fred ]
  pull_request:
    branches: [ main, develop, feature/* ]

jobs:
  python-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r prosperity/requirements-prosperity.txt
    - name: Report on code efficiency
      run: |
        python -m radon cc "prosperity/components/sensor.py"
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 prosperity/ --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 prosperity/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test coverage
      run: |
        pytest --cov="." prosperity/tests
    - name: Test with pytest
      run: |
        pytest prosperity/tests

  image-build:
    runs-on: ubuntu-latest
    needs: python-build
    
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Build and push image'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.PROSPERITY_CR }}
        username: ${{ secrets.PROSPERITY_CR_USERNAME }}
        password: ${{ secrets.PROSPERITY_CR_PASSWORD }}
    - run: |
        docker build . -t ${{ secrets.PROSPERITY_CR }}/prosperity:${{ github.sha }} 
        docker push ${{ secrets.PROSPERITY_CR }}/prosperity:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: image-build

    steps:
    - name: Deploy to Azure App Service for containers
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'prosperity-app'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: ${{ secrets.PROSPERITY_CR }}/prosperity:${{ github.sha }}